server:
  port: 6066

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hotel_micro
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: AUTH-SERVICE

  config:
    import: configserver:http://localhost:6065